"use client";

import { useState } from "react";
import type { PlannedImprovement } from "@/lib/tracking/schema";

type Option = { id: string; title?: string; name?: string };
type Props = { project: string; branch: string; expectedBranchCommit: string; record: PlannedImprovement; catalog: { services: Option[]; components: Option[]; areas: Option[] }; relationships: { proposals: Option[]; developmentLogs: Option[]; legacyCleanup: Option[] } };

export function EditPlannedImprovementForm({ project, branch, expectedBranchCommit, record, catalog, relationships }: Props) {
  const [title, setTitle] = useState(record.title); const [summary, setSummary] = useState(record.summary); const [goal, setGoal] = useState(record.goal); const [priority, setPriority] = useState(record.priority); const [status, setStatus] = useState(record.status); const [services, setServices] = useState(record.scope.services); const [components, setComponents] = useState(record.scope.components); const [areas, setAreas] = useState(record.scope.areas); const [proposalIds, setProposalIds] = useState(record.relationships.proposalIds); const [developmentLogIds, setDevelopmentLogIds] = useState(record.relationships.developmentLogIds); const [legacyCleanupIds, setLegacyCleanupIds] = useState(record.relationships.legacyCleanupIds); const [message, setMessage] = useState<string>();
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/tracking/planned-improvements", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ project, branch, expectedBranchCommit, record: { id: record.id, title, summary, goal, priority, status, categories: record.categories, scope: { services, components, areas }, relationships: { proposalIds, developmentLogIds, legacyCleanupIds } } }) }); const result = await response.json() as { error?: string }; if (!response.ok) { setMessage(result.error ?? "Tracking update failed."); return; } window.location.reload(); }
  return <details><summary>{record.id} — {record.title}</summary><form onSubmit={submit} className="tracking-form"><label>Title<input required value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Summary<textarea required value={summary} onChange={(event) => setSummary(event.target.value)} /></label><label>Goal<textarea required value={goal} onChange={(event) => setGoal(event.target.value)} /></label><label>Priority<select value={priority} onChange={(event) => setPriority(event.target.value as typeof priority)}><option value="low">low</option><option value="medium">medium</option><option value="high">high</option></select></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value as typeof status)}>{["backlog", "in_progress", "blocked", "completed"].map((item) => <option key={item} value={item}>{item}</option>)}</select></label><Choice label="Services" options={catalog.services} value={services} onChange={setServices} /><Choice label="Components" options={catalog.components} value={components} onChange={setComponents} /><Choice label="Areas" options={catalog.areas} value={areas} onChange={setAreas} /><Choice label="Proposals" options={relationships.proposals} value={proposalIds} onChange={setProposalIds} /><Choice label="Development logs" options={relationships.developmentLogs} value={developmentLogIds} onChange={setDevelopmentLogIds} /><Choice label="Legacy cleanup" options={relationships.legacyCleanup} value={legacyCleanupIds} onChange={setLegacyCleanupIds} /><button type="submit">Save planned improvement</button>{message ? <p role="status">{message}</p> : null}</form></details>;
}
function Choice({ label, options, value, onChange }: { label: string; options: Option[]; value: string[]; onChange: (value: string[]) => void }) { return <label>{label}<select multiple value={value} onChange={(event) => onChange(Array.from(event.target.selectedOptions, (option) => option.value))}>{options.map((option) => <option key={option.id} value={option.id}>{option.id} — {option.title ?? option.name}</option>)}</select></label>; }
