"use client";
import { useState } from "react";
import type { PlannedImprovement } from "@/lib/tracking/schema";
type Option = { id: string; title?: string; name?: string };
type Props = { project:string; branch:string; expectedBranchCommit:string; record:PlannedImprovement; catalog:{services:Option[];components:Option[];areas:Option[]}; relationships:{proposals:Option[];developmentLogs:Option[];legacyCleanup:Option[]} };
const categoryOptions=["architecture","data_integrity","database_safety","developer_experience","documentation","operational","reliability","security","testing"];
const values=(e:React.ChangeEvent<HTMLSelectElement>)=>Array.from(e.target.selectedOptions,x=>x.value);
export function EditPlannedImprovementForm({project,branch,expectedBranchCommit,record,catalog,relationships}:Props){
 const [title,setTitle]=useState(record.title),[summary,setSummary]=useState(record.summary),[goal,setGoal]=useState(record.goal),[priority,setPriority]=useState(record.priority),[status,setStatus]=useState(record.status),[categories,setCategories]=useState<string[]>(record.categories),[services,setServices]=useState(record.scope.services),[components,setComponents]=useState(record.scope.components),[areas,setAreas]=useState(record.scope.areas),[proposalIds,setProposalIds]=useState(record.relationships.proposalIds),[developmentLogIds,setDevelopmentLogIds]=useState(record.relationships.developmentLogIds),[legacyCleanupIds,setLegacyCleanupIds]=useState(record.relationships.legacyCleanupIds),[message,setMessage]=useState<string>();
 async function save(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/tracking/planned-improvements",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({project,branch,expectedBranchCommit,record:{id:record.id,title,summary,goal,priority,status,categories,scope:{services,components,areas},relationships:{proposalIds,developmentLogIds,legacyCleanupIds}}})});const x=await r.json();if(!r.ok){setMessage(x.error??"Tracking update failed.");return;}window.location.reload();}
 return <details><summary>{record.id} — {record.title}</summary><form onSubmit={save} className="tracking-form"><Text label="Title" value={title} set={setTitle}/><Text label="Summary" value={summary} set={setSummary}/><Text label="Goal" value={goal} set={setGoal}/><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}>{["low","medium","high"].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as typeof status)}>{["backlog","in_progress","blocked","completed"].map(x=><option key={x}>{x}</option>)}</select></label><Choice label="Categories" options={categoryOptions.map(id=>({id,name:id}))} value={categories} set={setCategories}/><Choice label="Services" options={catalog.services} value={services} set={setServices}/><Choice label="Components" options={catalog.components} value={components} set={setComponents}/><Choice label="Areas" options={catalog.areas} value={areas} set={setAreas}/><Choice label="Proposals" options={relationships.proposals} value={proposalIds} set={setProposalIds}/><Choice label="Development logs" options={relationships.developmentLogs} value={developmentLogIds} set={setDevelopmentLogIds}/><Choice label="Legacy cleanup" options={relationships.legacyCleanup} value={legacyCleanupIds} set={setLegacyCleanupIds}/><button>Save planned improvement</button>{message&&<p role="status">{message}</p>}</form></details>;
}
function Text({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label>{label}<textarea required value={value} onChange={e=>set(e.target.value)}/></label>}
function Choice({label,options,value,set}:{label:string;options:Option[];value:string[];set:(v:string[])=>void}){return <label>{label}<select multiple value={value} onChange={e=>set(values(e))}>{options.map(o=><option key={o.id} value={o.id}>{o.id} — {o.title??o.name}</option>)}</select></label>}
